basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the docs for REST API of Questions App.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Questions App API
  version: "1.0"
paths:
  /blocks/user/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: User ID to be blocked
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Block an user
      tags:
      - blocks
securityDefinitions:
  x-api-key:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
